// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require('dotenv').config();
const { defineConfig } = require('@prisma/config');
const path = require('path');

export default defineConfig({
  schema: path.join(__dirname, "prisma/schema.prisma"),
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL
  },
});
